### ISSUE TITLE
Drawio Default Theme + Overall look and feel

### ISSUE THREAD

**Issue by joshuaquek** [zapthedingbat/drawio-obsidian#11]
Hey @zapthedingbat ! This is a really awesome plugin, have been waiting for this for a while already. Thanks a lot for creating this.

Was wondering if its possible to give the option to use the default Drawio theme view as well as the default box and arrows look and feel. Also the grid background seems to be missing too.

Currently the boxes and arrows have this sketchy feel, was wondering if we can have it back to the original view. Reason being that I use Drawio a lot to draw professional architecture diagrams.

**Comment by joshuaquek** [comment]
Update - managed to get the grid background, but am not able to switch off the "Sketch" styling

![image](https://user-images.githubusercontent.com/5335756/133032402-23495d77-7241-4940-a578-ddbaeae51043.png)

**Comment by zapthedingbat** [comment]
Good news, this is already possable. You can change the Theme, Dark/Light mode and the "Sketch" option in the settings dialog under:

Settings > Diagrams

Change the Theme to "Full" and Disable "Sketch" should do what you want.
![image](https://user-images.githubusercontent.com/196548/133658587-70e74856-8ac2-413c-b63f-2d1b12b37109.png)

**Comment by joshuaquek** [comment]
AWESOME! Tried it and it works!! thank you @zapthedingbat !!!
