### ISSUE TITLE
Add hotkey for insert diagram

### ISSUE THREAD

**Issue by seagullmouse** [zapthedingbat/drawio-obsidian#16]
I'd like to assign a hotkey to `Insert new diagram` but it is not listed as an action in the hotkey list. Other plugins allow assigning of hotkeys so it must be possible.

Thanks

**Comment by aaylnx** [comment]
This would be great. I just installed this plugin, but I cannot figure out how to invoke it and use it. Am I missing the documentation for this? The screenshot of it looks great, but I can't figure out how to use it I'm afraid.

**Comment by jiri** [comment]
I'll add to this that I'd also be able to insert a new diagram using the command palette (ctrl-p). I'm adding it here because my understanding is that hotkeys and commands are tightly coupled in Obsidian :)

**Comment by bjorndotwork** [comment]
This. Great plugin, but please, please, please add support for command palette command(s) and hotkey(s).
