### ISSUE TITLE
Export to PNG format

### ISSUE THREAD

**Issue by VasylTyshchuk** [zapthedingbat/drawio-obsidian#5]
It would be good to have some basic exporting options, such as export to PNG or JPEG.

**Comment by zapthedingbat** [comment]
Thanks for the feedback. I think the draw.io app can do this so I think it should just be a matter of creating the right user interface to expose it. I'll take a look.

**Comment by zapthedingbat** [comment]
Added export to png option in version 1.4.0 https://github.com/zapthedingbat/drawio-obsidian/releases/tag/1.4.0

I ended up doing this in obsidian rather than using the export feature of draw.io the export works in preview and edit view.

**Comment by HananoshikaYomaru** [comment]
export as png doesn't work. The image is not generated.
