### ISSUE TITLE
核心插件文件列表没了，而且页面位置错误

### ISSUE THREAD

**Issue by ydh1cnn6** [zapthedingbat/drawio-obsidian#88]
![image](https://github.com/zapthedingbat/drawio-obsidian/assets/64244993/8b193145-0bdf-4c66-a905-f061473064b6)
点击图标后直接跳转如下页面：
![image](https://github.com/zapthedingbat/drawio-obsidian/assets/64244993/84be0ab0-40e4-4852-b133-c693d8b6bb67)
问题：核心插件文件列表图标消失，而且页面位置错误，覆盖了文件列表。（通过重启可恢复核心插件文件列表图标，但每次点击插件图标都要重启）

**Comment by xh542428798** [comment]
I am the same problem

**Comment by xh542428798** [comment]
We can build by ourself! I succeed!

**Comment by sapphire008** [comment]
[main.txt](https://github.com/zapthedingbat/drawio-obsidian/files/13721053/main.txt)
Okay, I was able to rebuilt the plugin, this is the file you would need to replace under `.obsidian/plugins/drawio-obsidian`, which should fix the problem.

**Comment by ydh1cnn6** [comment]
> [main.txt](https://github.com/zapthedingbat/drawio-obsidian/files/13721053/main.txt) 好的，我能够重建插件，这是您需要替换的文件，这应该可以解决问题。将扩展名从 .txt 更改为 .js`.obsidian/plugins/drawio-obsidian`

谢谢，这个方式确实可以解决这个问题
